/**
 * Manual pages for all terminal commands.
 * Source of truth for the `man` command (mirrors shipped terminal behavior).
 */
export const manPages: Record<string, string[]> = {
  grep: [
    "",
    "NAME",
    "    grep - filter piped lines by substring",
    "",
    "SYNOPSIS",
    "    <command> | grep <pattern> [-v]",
    "",
    "DESCRIPTION",
    "    Keeps lines containing the pattern (case-insensitive).",
    "    With -v, keeps lines that do NOT match. Only usable",
    "    after a pipe.",
    "",
    "EXAMPLES",
    "    ls | grep dune",
    "    history | grep theme",
    "    notes | grep -v 2025",
    "",
    "SEE ALSO",
    "    head, tail, wc, sort",
    "",
  ],
  head: [
    "",
    "NAME",
    "    head - show the first n piped lines",
    "",
    "SYNOPSIS",
    "    <command> | head [n]",
    "",
    "DESCRIPTION",
    "    Shows the first n lines of piped input (default 10).",
    "",
    "EXAMPLES",
    "    ls | head 5",
    "",
    "SEE ALSO",
    "    tail, grep",
    "",
  ],
  tail: [
    "",
    "NAME",
    "    tail - show the last n piped lines",
    "",
    "SYNOPSIS",
    "    <command> | tail [n]",
    "",
    "DESCRIPTION",
    "    Shows the last n lines of piped input (default 10).",
    "",
    "EXAMPLES",
    "    history | tail 3",
    "",
    "SEE ALSO",
    "    head, grep",
    "",
  ],
  wc: [
    "",
    "NAME",
    "    wc - count piped lines",
    "",
    "SYNOPSIS",
    "    <command> | wc",
    "",
    "DESCRIPTION",
    "    Counts non-empty lines of piped input.",
    "",
    "EXAMPLES",
    "    ls | wc",
    "    search king | wc",
    "",
    "SEE ALSO",
    "    grep, head, tail",
    "",
  ],
  sort: [
    "",
    "NAME",
    "    sort - sort piped lines",
    "",
    "SYNOPSIS",
    "    <command> | sort [-r]",
    "",
    "DESCRIPTION",
    "    Sorts piped lines alphabetically (case-insensitive).",
    "    With -r, sorts in reverse order.",
    "",
    "EXAMPLES",
    "    ls | sort",
    "    ls | sort -r",
    "",
    "SEE ALSO",
    "    grep, head, tail, wc",
    "",
  ],
  history: [
    "",
    "NAME",
    "    history - show command history",
    "",
    "SYNOPSIS",
    "    history",
    "",
    "DESCRIPTION",
    "    Lists the commands you have run this session, numbered.",
    "    Re-run the previous command with !! or the nth with !n.",
    "",
    "EXAMPLES",
    "    history",
    "    history | grep theme",
    "    !!",
    "    !3",
    "",
  ],
  wall: [
    "",
    "NAME",
    "    wall - the guestbook wall",
    "",
    "SYNOPSIS",
    "    wall [message]",
    "",
    "DESCRIPTION",
    "    With no arguments, shows the latest messages on the wall.",
    "    With a message, signs the wall as guest (140 chars max,",
    "    no links, 3 posts per hour).",
    "",
    "EXAMPLES",
    "    wall",
    "    wall hello from the terminal",
    "",
  ],
  highscores: [
    "",
    "NAME",
    "    highscores - arcade leaderboards",
    "",
    "SYNOPSIS",
    "    highscores [game]",
    "",
    "DESCRIPTION",
    "    Shows the top scores for every game, or the top 10 for one.",
    "    Games: tron, pacman, basketball, typespeed, snake.",
    "",
    "EXAMPLES",
    "    highscores",
    "    highscores snake",
    "",
  ],
  stats: [
    "",
    "NAME",
    "    stats - collection statistics as bar charts",
    "",
    "SYNOPSIS",
    "    stats",
    "",
    "DESCRIPTION",
    "    ASCII bar charts over the collections: top book and vinyl",
    "    genres, formats, and hardware status.",
    "",
    "EXAMPLES",
    "    stats",
    "    stats | grep Fiction",
    "",
  ],
  tour: [
    "",
    "NAME",
    "    tour - guided demo of the terminal",
    "",
    "SYNOPSIS",
    "    tour",
    "",
    "DESCRIPTION",
    "    Types and runs a scripted sequence of real commands with a",
    "    typewriter effect. Press any key to take over at any point.",
    "",
    "EXAMPLES",
    "    tour",
    "",
  ],
  cowsay: [
    "",
    "NAME",
    "    cowsay - a cow says things",
    "",
    "SYNOPSIS",
    "    cowsay <text>",
    "",
    "DESCRIPTION",
    "    An ASCII cow announces your message to the terminal.",
    "",
    "EXAMPLES",
    "    cowsay moo",
    "    cowsay hire zachary",
    "",
  ],

  man: [
    "",
    "NAME",
    "    man - display manual pages",
    "",
    "SYNOPSIS",
    "    man [command]",
    "",
    "DESCRIPTION",
    "    Display detailed documentation for terminal commands.",
    "    Without arguments, lists all available manual pages.",
    "",
    "EXAMPLES",
    "    man ls        View documentation for ls",
    "    man game      Learn about available games",
    "",
  ],
  ls: [
    "",
    "NAME",
    "    ls - list directory contents",
    "",
    "SYNOPSIS",
    "    ls [path]",
    "",
    "DESCRIPTION",
    "    List files and directories in the current or specified",
    "    directory. Use with cd to navigate the file system.",
    "",
    "EXAMPLES",
    "    ls            List current directory",
    "    ls books      List contents of books directory",
    "",
    "SEE ALSO",
    "    cd, pwd, cat",
    "",
  ],
  cd: [
    "",
    "NAME",
    "    cd - change directory",
    "",
    "SYNOPSIS",
    "    cd [directory]",
    "",
    "DESCRIPTION",
    "    Change the current working directory. Use ~ for home,",
    "    .. for parent directory, or specify a path.",
    "",
    "EXAMPLES",
    "    cd books      Navigate to books",
    "    cd ..         Go up one level",
    "    cd ~          Return home",
    "",
    "SEE ALSO",
    "    ls, pwd",
    "",
  ],
  pwd: [
    "",
    "NAME",
    "    pwd - print working directory",
    "",
    "SYNOPSIS",
    "    pwd",
    "",
    "DESCRIPTION",
    "    Display the full path of the current directory.",
    "",
  ],
  cat: [
    "",
    "NAME",
    "    cat - display file contents",
    "",
    "SYNOPSIS",
    "    cat <file>",
    "",
    "DESCRIPTION",
    "    Display the raw contents of a file. For formatted",
    "    output of collection items, use 'view' instead.",
    "",
    "SEE ALSO",
    "    view",
    "",
  ],
  view: [
    "",
    "NAME",
    "    view - display formatted file contents",
    "",
    "SYNOPSIS",
    "    view <file>",
    "",
    "DESCRIPTION",
    "    Display file contents with nice formatting. Works best",
    "    with collection items in ~/books, ~/vinyl, ~/hardware,",
    "    and blog posts in ~/notes.",
    "",
    "EXAMPLES",
    "    cd books",
    "    view dune",
    "    cd ~/notes",
    "    view welcome-young-explorers-",
    "",
    "SEE ALSO",
    "    cat, ls",
    "",
  ],
  search: [
    "",
    "NAME",
    "    search - search within collections",
    "",
    "SYNOPSIS",
    "    search <term>",
    "",
    "DESCRIPTION",
    "    Search the current collection for items matching the",
    "    given term. Searches titles and authors/artists.",
    "    Must be in ~/books, ~/vinyl, ~/hardware, or ~/notes.",
    "",
    "EXAMPLES",
    "    cd vinyl",
    "    search daft punk",
    "    cd ~/notes",
    "    search welcome",
    "",
    "SEE ALSO",
    "    genre, format, type",
    "",
  ],
  genre: [
    "",
    "NAME",
    "    genre - filter by genre",
    "",
    "SYNOPSIS",
    "    genre [name]",
    "",
    "DESCRIPTION",
    "    Without arguments, lists all genres in the collection.",
    "    With a genre name, shows items matching that genre.",
    "    Works in ~/books and ~/vinyl.",
    "",
    "EXAMPLES",
    "    genre              List all genres",
    "    genre rock         Show rock albums",
    "",
    "SEE ALSO",
    "    search, format",
    "",
  ],
  format: [
    "",
    "NAME",
    "    format - filter by format",
    "",
    "SYNOPSIS",
    "    format [type]",
    "",
    "DESCRIPTION",
    "    Without arguments, lists all formats in the collection.",
    "    With a format type, shows items in that format.",
    "    Works in ~/books and ~/vinyl.",
    "",
    "EXAMPLES",
    "    format             List all formats",
    "    format hardcover   Show hardcover books",
    "",
    "SEE ALSO",
    "    search, genre",
    "",
  ],
  type: [
    "",
    "NAME",
    "    type - filter hardware by type",
    "",
    "SYNOPSIS",
    "    type [name]",
    "",
    "DESCRIPTION",
    "    Without arguments, lists all hardware types.",
    "    With a type name, shows devices of that type.",
    "    Only works in ~/hardware.",
    "",
    "EXAMPLES",
    "    type               List all types",
    "    type laptop        Show laptops",
    "",
    "SEE ALSO",
    "    search",
    "",
  ],
  game: [
    "",
    "NAME",
    "    game - play terminal games",
    "",
    "SYNOPSIS",
    "    game <type>",
    "",
    "DESCRIPTION",
    "    Launch a terminal game. Press Ctrl+C to quit any game.",
    "",
    "GAMES",
    "    number      Guess a number between 1-100",
    "    wordle      Daily word puzzle (game wordle practice for a random round)",
    "    trivia      Answer 5 trivia questions",
    "    blackjack   Play 21 against the dealer",
    "    rps         Rock Paper Scissors",
    "    tron        Light Cycle Arcade Game",
    "    pacman      Classic Maze Chase",
    "    basketball  Arcade Hoops",
    "    typespeed   Typing speed test (posts to the leaderboard)",
    "    snake       Eat, grow, repeat",
    "",
    "EXAMPLES",
    "    game wordle",
    "    game wordle practice",
    "    game snake",
    "",
  ],
  notes: [
    "",
    "NAME",
    "    notes - read blog posts and updates",
    "",
    "SYNOPSIS",
    "    notes [number]",
    "",
    "DESCRIPTION",
    "    View blog posts and site updates. Without arguments,",
    "    displays a numbered list of available notes. With a",
    "    number, displays that note.",
    "",
    "EXAMPLES",
    "    notes        List all notes",
    "    notes 1      Read the first note",
    "",
    "SEE ALSO",
    "    view, cat",
    "",
  ],
  suggest: [
    "",
    "NAME",
    "    suggest - submit a game suggestion",
    "",
    "SYNOPSIS",
    "    suggest",
    "",
    "DESCRIPTION",
    "    Opens an interactive prompt to submit a game idea or",
    "    suggestion. Your suggestion will be sent via email.",
    "    Type 'cancel' to exit without submitting.",
    "",
    "EXAMPLES",
    "    suggest",
    "    > A multiplayer snake game",
    "",
    "SEE ALSO",
    "    game",
    "",
  ],
  theme: [
    "",
    "NAME",
    "    theme - change terminal color theme",
    "",
    "SYNOPSIS",
    "    theme [name]",
    "",
    "DESCRIPTION",
    "    Without arguments, lists available themes.",
    "    With a theme name, applies that theme.",
    "    Theme preference is saved to localStorage.",
    "",
    "THEMES",
    "    midnight, tokyonight, dracula, gruvbox, nord, monokai",
    "",
    "EXAMPLES",
    "    theme              List themes",
    "    theme dracula      Apply Dracula theme",
    "",
    "SEE ALSO",
    "    font, neofetch",
    "",
  ],
  font: [
    "",
    "NAME",
    "    font - change terminal font",
    "",
    "SYNOPSIS",
    "    font [name]",
    "",
    "DESCRIPTION",
    "    Without arguments, lists available fonts.",
    "    With a font name, applies that font.",
    "    Font preference is saved to localStorage.",
    "",
    "FONTS",
    "    jetbrains, fira, source, ibm, hack, mono",
    "",
    "EXAMPLES",
    "    font               List fonts",
    "    font fira          Apply Fira Code",
    "",
    "SEE ALSO",
    "    theme, neofetch",
    "",
  ],
  sound: [
    "",
    "NAME",
    "    sound - toggle sound effects",
    "",
    "SYNOPSIS",
    "    sound [on|off]",
    "",
    "DESCRIPTION",
    "    Enable or disable retro sound effects. When enabled, plays",
    "    keyclick sounds on typing, beeps on errors, and chimes on",
    "    success. Sound preference is saved to localStorage.",
    "    Without arguments, displays current sound state.",
    "",
    "EXAMPLES",
    "    sound on        Enable sound effects",
    "    sound off       Disable sound effects",
    "    sound           Show current state",
    "",
  ],
  neofetch: [
    "",
    "NAME",
    "    neofetch - display system information",
    "",
    "SYNOPSIS",
    "    neofetch",
    "",
    "DESCRIPTION",
    "    Display terminal configuration and collection stats",
    "    in the style of the classic neofetch utility.",
    "",
  ],
  mkdir: [
    "",
    "NAME",
    "    mkdir - create directory",
    "",
    "SYNOPSIS",
    "    mkdir <name>",
    "",
    "DESCRIPTION",
    "    Create a new directory in the current location.",
    "",
    "SEE ALSO",
    "    touch, rm, ls",
    "",
  ],
  touch: [
    "",
    "NAME",
    "    touch - create empty file",
    "",
    "SYNOPSIS",
    "    touch <name>",
    "",
    "DESCRIPTION",
    "    Create a new empty file in the current location.",
    "",
    "SEE ALSO",
    "    mkdir, rm, cat",
    "",
  ],
  rm: [
    "",
    "NAME",
    "    rm - remove file or directory",
    "",
    "SYNOPSIS",
    "    rm <path>",
    "",
    "DESCRIPTION",
    "    Remove a file or empty directory.",
    "",
    "SEE ALSO",
    "    mkdir, touch",
    "",
  ],
  about: [
    "",
    "NAME",
    "    about - about the author",
    "",
    "SYNOPSIS",
    "    about",
    "",
    "DESCRIPTION",
    "    Display information about Zachary.",
    "",
    "SEE ALSO",
    "    contact, projects",
    "",
  ],
  contact: [
    "",
    "NAME",
    "    contact - contact information",
    "",
    "SYNOPSIS",
    "    contact",
    "",
    "DESCRIPTION",
    "    Display email and social links.",
    "",
    "SEE ALSO",
    "    about, projects",
    "",
  ],
  projects: [
    "",
    "NAME",
    "    projects - view projects",
    "",
    "SYNOPSIS",
    "    projects",
    "",
    "DESCRIPTION",
    "    Open GitHub profile in a new tab.",
    "",
    "SEE ALSO",
    "    about, contact",
    "",
  ],
  clear: [
    "",
    "NAME",
    "    clear - clear terminal screen",
    "",
    "SYNOPSIS",
    "    clear",
    "",
    "DESCRIPTION",
    "    Clear all terminal output. Also available via Ctrl+L.",
    "",
  ],
  whoami: [
    "",
    "NAME",
    "    whoami - display current user",
    "",
    "SYNOPSIS",
    "    whoami",
    "",
    "DESCRIPTION",
    "    Print the current username.",
    "",
  ],
  date: [
    "",
    "NAME",
    "    date - display current date and time",
    "",
    "SYNOPSIS",
    "    date",
    "",
    "DESCRIPTION",
    "    Print the current date and time.",
    "",
  ],
  echo: [
    "",
    "NAME",
    "    echo - display text",
    "",
    "SYNOPSIS",
    "    echo [text...]",
    "",
    "DESCRIPTION",
    "    Print the given text to the terminal.",
    "",
    "EXAMPLES",
    "    echo hello world",
    "",
  ],
  help: [
    "",
    "NAME",
    "    help - display command summary",
    "",
    "SYNOPSIS",
    "    help",
    "",
    "DESCRIPTION",
    "    Display a quick reference of available commands.",
    "    For detailed documentation, use 'man <command>'.",
    "",
    "SEE ALSO",
    "    man",
    "",
  ],
}
