export const manPages: Record<string, string[]> = {
  ls: [
    '',
    'NAME',
    '    ls - list directory contents',
    '',
    'SYNOPSIS',
    '    ls [path]',
    '',
    'DESCRIPTION',
    '    List files and directories in the current or specified',
    '    directory. Use with cd to navigate the file system.',
    '',
    'EXAMPLES',
    '    ls            List current directory',
    '    ls books      List contents of books directory',
    '',
    'SEE ALSO',
    '    cd, pwd, cat',
    '',
  ],
  cd: [
    '',
    'NAME',
    '    cd - change directory',
    '',
    'SYNOPSIS',
    '    cd [path]',
    '',
    'DESCRIPTION',
    '    Change the current working directory. Use ~ for home,',
    '    .. for parent directory, and / for absolute paths.',
    '',
    'EXAMPLES',
    '    cd books      Enter books directory',
    '    cd ..         Go up one level',
    '    cd ~          Return to home',
    '',
    'SEE ALSO',
    '    ls, pwd',
    '',
  ],
  pwd: [
    '',
    'NAME',
    '    pwd - print working directory',
    '',
    'SYNOPSIS',
    '    pwd',
    '',
    'DESCRIPTION',
    '    Print the full path of the current working directory.',
    '',
    'SEE ALSO',
    '    cd, ls',
    '',
  ],
  cat: [
    '',
    'NAME',
    '    cat - display file contents',
    '',
    'SYNOPSIS',
    '    cat <file>',
    '',
    'DESCRIPTION',
    '    Display the raw contents of a file. For formatted',
    "    output of collection items, use 'view' instead.",
    '',
    'SEE ALSO',
    '    view',
    '',
  ],
  view: [
    '',
    'NAME',
    '    view - display formatted file contents',
    '',
    'SYNOPSIS',
    '    view <file>',
    '',
    'DESCRIPTION',
    '    Display file contents with nice formatting. Works best',
    '    with collection items in ~/books, ~/vinyl, ~/hardware.',
    '',
    'EXAMPLES',
    '    cd books',
    '    view dune',
    '',
    'SEE ALSO',
    '    cat, ls',
    '',
  ],
  search: [
    '',
    'NAME',
    '    search - search within collections',
    '',
    'SYNOPSIS',
    '    search <term>',
    '',
    'DESCRIPTION',
    '    Search the current collection for items matching the',
    '    given term. Searches titles and authors/artists.',
    '    Must be in ~/books, ~/vinyl, or ~/hardware.',
    '',
    'EXAMPLES',
    '    cd vinyl',
    '    search daft punk',
    '',
    'SEE ALSO',
    '    genre, format, type',
    '',
  ],
  genre: [
    '',
    'NAME',
    '    genre - filter by genre',
    '',
    'SYNOPSIS',
    '    genre [name]',
    '',
    'DESCRIPTION',
    '    Without arguments, lists all genres in the collection.',
    '    With a genre name, shows items matching that genre.',
    '    Works in ~/books and ~/vinyl.',
    '',
    'EXAMPLES',
    '    genre              List all genres',
    '    genre rock         Show rock albums',
    '',
    'SEE ALSO',
    '    search, format',
    '',
  ],
  format: [
    '',
    'NAME',
    '    format - filter by format',
    '',
    'SYNOPSIS',
    '    format [type]',
    '',
    'DESCRIPTION',
    '    Without arguments, lists all formats in the collection.',
    '    With a format type, shows items in that format.',
    '    Works in ~/books and ~/vinyl.',
    '',
    'EXAMPLES',
    '    format             List all formats',
    '    format hardcover   Show hardcover books',
    '',
    'SEE ALSO',
    '    search, genre',
    '',
  ],
  type: [
    '',
    'NAME',
    '    type - filter hardware by type',
    '',
    'SYNOPSIS',
    '    type [name]',
    '',
    'DESCRIPTION',
    '    Without arguments, lists all hardware types.',
    '    With a type name, shows devices of that type.',
    '    Only works in ~/hardware.',
    '',
    'EXAMPLES',
    '    type               List all types',
    '    type laptop        Show laptops',
    '',
    'SEE ALSO',
    '    search',
    '',
  ],
  game: [
    '',
    'NAME',
    '    game - play terminal games',
    '',
    'SYNOPSIS',
    '    game <type>',
    '',
    'DESCRIPTION',
    '    Launch a terminal game. Press Ctrl+C to quit any game.',
    '',
    'GAMES',
    '    number      Guess a number between 1-100',
    '    wordle      Guess the 5-letter word in 6 tries',
    '    trivia      Answer 5 trivia questions',
    '    blackjack   Play 21 against the dealer',
    '    rps         Rock Paper Scissors',
    '    tron        Light Cycle Arcade Game',
    '',
    'EXAMPLES',
    '    game wordle',
    '    game tron',
    '',
  ],
  theme: [
    '',
    'NAME',
    '    theme - change terminal color theme',
    '',
    'SYNOPSIS',
    '    theme [name]',
    '',
    'DESCRIPTION',
    '    Without arguments, lists available themes.',
    '    With a theme name, applies that theme.',
    '    Theme preference is saved to localStorage.',
    '',
    'THEMES',
    '    lumon, tokyonight, dracula, gruvbox, nord, monokai',
    '',
    'EXAMPLES',
    '    theme              List themes',
    '    theme dracula      Apply Dracula theme',
    '',
    'SEE ALSO',
    '    font, neofetch',
    '',
  ],
  font: [
    '',
    'NAME',
    '    font - change terminal font',
    '',
    'SYNOPSIS',
    '    font [name]',
    '',
    'DESCRIPTION',
    '    Without arguments, lists available fonts.',
    '    With a font name, applies that font.',
    '    Font preference is saved to localStorage.',
    '',
    'FONTS',
    '    jetbrains, fira, source, ibm, hack, mono',
    '',
    'EXAMPLES',
    '    font               List fonts',
    '    font fira          Apply Fira Code',
    '',
    'SEE ALSO',
    '    theme, neofetch',
    '',
  ],
  neofetch: [
    '',
    'NAME',
    '    neofetch - display system information',
    '',
    'SYNOPSIS',
    '    neofetch',
    '',
    'DESCRIPTION',
    '    Display terminal configuration and collection stats',
    '    in the style of the classic neofetch utility.',
    '',
  ],
  mkdir: [
    '',
    'NAME',
    '    mkdir - create directory',
    '',
    'SYNOPSIS',
    '    mkdir <name>',
    '',
    'DESCRIPTION',
    '    Create a new directory in the current location.',
    '',
    'SEE ALSO',
    '    touch, rm, ls',
    '',
  ],
  touch: [
    '',
    'NAME',
    '    touch - create empty file',
    '',
    'SYNOPSIS',
    '    touch <name>',
    '',
    'DESCRIPTION',
    '    Create a new empty file in the current location.',
    '',
    'SEE ALSO',
    '    mkdir, rm, cat',
    '',
  ],
  rm: [
    '',
    'NAME',
    '    rm - remove file or directory',
    '',
    'SYNOPSIS',
    '    rm <path>',
    '',
    'DESCRIPTION',
    '    Remove a file or empty directory.',
    '',
    'SEE ALSO',
    '    mkdir, touch',
    '',
  ],
  about: [
    '',
    'NAME',
    '    about - about the author',
    '',
    'SYNOPSIS',
    '    about',
    '',
    'DESCRIPTION',
    '    Display information about Zachary.',
    '',
    'SEE ALSO',
    '    contact, projects',
    '',
  ],
  contact: [
    '',
    'NAME',
    '    contact - contact information',
    '',
    'SYNOPSIS',
    '    contact',
    '',
    'DESCRIPTION',
    '    Display email and social links.',
    '',
    'SEE ALSO',
    '    about, projects',
    '',
  ],
  projects: [
    '',
    'NAME',
    '    projects - view projects',
    '',
    'SYNOPSIS',
    '    projects',
    '',
    'DESCRIPTION',
    '    Open GitHub profile in a new tab.',
    '',
    'SEE ALSO',
    '    about, contact',
    '',
  ],
  clear: [
    '',
    'NAME',
    '    clear - clear terminal screen',
    '',
    'SYNOPSIS',
    '    clear',
    '',
    'DESCRIPTION',
    '    Clear all terminal output. Also available via Ctrl+L.',
    '',
  ],
  whoami: [
    '',
    'NAME',
    '    whoami - display current user',
    '',
    'SYNOPSIS',
    '    whoami',
    '',
    'DESCRIPTION',
    '    Print the current username.',
    '',
  ],
  date: [
    '',
    'NAME',
    '    date - display current date and time',
    '',
    'SYNOPSIS',
    '    date',
    '',
    'DESCRIPTION',
    '    Print the current date and time.',
    '',
  ],
  echo: [
    '',
    'NAME',
    '    echo - display text',
    '',
    'SYNOPSIS',
    '    echo [text...]',
    '',
    'DESCRIPTION',
    '    Print the given text to the terminal.',
    '',
    'EXAMPLES',
    '    echo hello world',
    '',
  ],
  help: [
    '',
    'NAME',
    '    help - display command summary',
    '',
    'SYNOPSIS',
    '    help',
    '',
    'DESCRIPTION',
    '    Display a quick reference of available commands.',
    "    For detailed documentation, use 'man <command>'.",
    '',
    'SEE ALSO',
    '    man',
    '',
  ],
}
